#!/usr/bin/env bash
#script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me
https:\/\/github.com\/kadelite permanent;/" /etc/nginx/sites-available/default
service nginx start
